/* ============================================================
   NEMESIS Command Deck — Trade Routes board
   Best buy→sell commodity routes from a UEX snapshot (data/trade-routes.json,
   regenerated by scripts/ingest-trade.py on a schedule). Prices are a SNAPSHOT,
   not live — the UI shows the snapshot time and a staleness note. Includes a
   cargo-SCU calculator (profit per run) and legal/system filters.
   ============================================================ */
import { loadJSON } from './data-loader.js';
import { formatNumber } from './stats-calculator.js';

let ROOT = null;
let DATA = null;
let scu = 0;
let legal = 'all';        // all | legal | illegal
let sameSystemOnly = false;
let search = '';
let sort = { col: 'profit', dir: -1 };

function esc(s) { return (s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }

const COLS = [
  { k: 'commodity', l: 'Commodity', num: false },
  { k: 'buyPrice', l: 'Buy', num: true, fmt: (v, r) => `${formatNumber(v)}<span class="tr-loc">${esc(r.buyTerminal || '')}${r.buySystem ? ' · ' + esc(r.buySystem) : ''}</span>` },
  { k: 'sellPrice', l: 'Sell', num: true, fmt: (v, r) => `${formatNumber(v)}<span class="tr-loc">${esc(r.sellTerminal || '')}${r.sellSystem ? ' · ' + esc(r.sellSystem) : ''}</span>` },
  { k: 'profit', l: 'Profit/SCU', num: true, fmt: v => `<b class="tr-profit">+${formatNumber(v)}</b>` },
  { k: 'marginPct', l: 'Margin', num: true, fmt: v => v + '%' },
  { k: 'run', l: 'Per run', num: true, fmt: (v, r) => scu > 0 ? formatNumber(r.profit * scu) : '—' },
];

export async function initTrade(root) {
  ROOT = root;
  try {
    DATA = await loadJSON('trade-routes.json');
  } catch (e) {
    root.innerHTML = `<div class="empty-state" style="color:var(--status-crit)"><h3>Trade data unavailable</h3><p>data/trade-routes.json failed to load. ${e.message}</p></div>`;
    return;
  }
  render();
}

function render() {
  const routes = (DATA.routes || []).filter(r => {
    if (legal === 'legal' && r.illegal) return false;
    if (legal === 'illegal' && !r.illegal) return false;
    if (sameSystemOnly && !r.sameSystem) return false;
    if (search && !(r.commodity || '').toLowerCase().includes(search)) return false;
    return true;
  });
  const sorted = [...routes].sort((a, b) => {
    const av = sort.col === 'run' ? a.profit : a[sort.col];
    const bv = sort.col === 'run' ? b.profit : b[sort.col];
    if (typeof av === 'number') return (av - bv) * sort.dir;
    return String(av).localeCompare(String(bv)) * sort.dir;
  });

  const head = COLS.map(c => `<th data-col="${c.k}" class="${c.num ? 'num' : ''}${sort.col === c.k ? ' sorted' : ''}">${c.l}${sort.col === c.k ? (sort.dir > 0 ? ' ▲' : ' ▼') : ''}</th>`).join('');
  const rows = sorted.map(r => `<tr>${COLS.map(c => {
    const v = c.k === 'run' ? r.profit : r[c.k];
    const disp = c.fmt ? c.fmt(v, r) : esc(String(v));
    return `<td class="${c.num ? 'num' : ''}">${disp}</td>`;
  }).join('')}<td>${r.illegal ? '<span class="cf-conf cf-crit">illegal</span>' : ''}${r.sameSystem ? '<span class="cf-conf cf-ok">1-system</span>' : ''}</td></tr>`).join('')
    || '<tr><td colspan="7" class="src-note">No routes match this filter.</td></tr>';

  ROOT.innerHTML = `
    <div class="ph-head"><h2>Trade Routes</h2>
      <div class="ef-sub">Best buy→sell commodity runs ranked by profit per SCU. Enter your cargo capacity to see profit per trip.</div></div>

    <div class="craft-status"><span class="ps-dot"></span><span>UEX snapshot <b>${esc(DATA.snapshot || 'unknown')}</b> · ${DATA.count || 0} routes · prices drift over trade cycles — this is a periodic snapshot, <b>not live</b>. Re-check before a big haul.</span></div>

    <div class="trade-toolbar">
      <label class="trade-scu">Cargo SCU <input type="number" id="trScu" min="0" placeholder="e.g. 96" value="${scu || ''}"></label>
      <div class="fleet-filters">
        <button class="fl-chip${legal === 'all' ? ' active' : ''}" data-legal="all">All</button>
        <button class="fl-chip${legal === 'legal' ? ' active' : ''}" data-legal="legal">Legal</button>
        <button class="fl-chip${legal === 'illegal' ? ' active' : ''}" data-legal="illegal">Illegal</button>
        <button class="fl-chip${sameSystemOnly ? ' active' : ''}" id="trSameSys">Single-system only</button>
      </div>
      <input type="text" class="search-input trade-search" id="trSearch" placeholder="Search commodity..." value="${esc(search)}">
    </div>

    <div class="panel fleet-tablewrap">
      <table class="fleet-table trade-table"><thead><tr>${head}<th></th></tr></thead><tbody>${rows}</tbody></table>
    </div>
    <div class="src-note">Source: UEX Corp (uexcorp.space), community-run. Prices are player-reported and approximate. Unofficial — not affiliated with Cloud Imperium Games.</div>`;

  const si = ROOT.querySelector('#trScu');
  si.oninput = () => { scu = Math.max(0, parseInt(si.value, 10) || 0); render(); restoreFocus('#trScu'); };
  const se = ROOT.querySelector('#trSearch');
  se.oninput = () => { search = se.value.toLowerCase().trim(); render(); restoreFocus('#trSearch'); };
  ROOT.querySelectorAll('[data-legal]').forEach(b => b.onclick = () => { legal = b.dataset.legal; render(); });
  const ss = ROOT.querySelector('#trSameSys');
  if (ss) ss.onclick = () => { sameSystemOnly = !sameSystemOnly; render(); };
  ROOT.querySelectorAll('.trade-table th[data-col]').forEach(th => th.onclick = () => { const c = th.dataset.col; if (sort.col === c) sort.dir *= -1; else { sort.col = c; sort.dir = -1; } render(); });
}

function restoreFocus(sel) {
  const el = ROOT.querySelector(sel);
  if (el) { el.focus(); const v = el.value; el.value = ''; el.value = v; }
}
